### ISSUE TITLE
ENH: Add support for dask and rapids

### ISSUE THREAD

**Issue by zbrookle** [zbrookle/dataframe_sql#16]

**Comment by acivitillo** [comment]
Thanks for this, me and my team use dask and it makes sense to run SQL on top of parquet files on AWS S3 using something like this rather than a completely different product like Spark or AWS Spectrum.

What are your plans with this library? I see you are parsing the SQL with lark and mapping SQL objects to Pandas objects. I am trying to understand where you want to bring this. In theory with dask you could have this doing what spark sql or apache drill do. What are your thoughts?

**Comment by zbrookle** [comment]
@acivitillo Yes thanks for asking! That's exactly where the project is going. It always seemed strange to me that spark was the go-to program when someone wants to use sql with an open source data processing framework when the same thing could be done for all the python based frameworks, so this package is meant to fill that gap in capability

**Comment by acivitillo** [comment]
Will your dask support be available once Ibis adds theirs?

Seems they plan to add support: https://ibis-project.org/

**Comment by zbrookle** [comment]
@acivitillo Yes, the moment ibis finishes dask support I’ll be adding that into this package
